version: '3.8'

services:
  # --- 1. ADATBÁZIS ---
  postgres-db:
    image: postgres:16-alpine
    container_name: phone_shop_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
      - POSTGRES_DB=phonedb
    ports:
      - "5436:5432" # KÍVÜL: 5436, BELÜL: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- 2. FRONTEND ---
  frontend:
    build: ./frontend # Itt keresi a fenti Dockerfile-t
    container_name: phone_shop_frontend
    ports:
      - "3010:3000" # KÍVÜL: 3010, BELÜL: 3000
    volumes:
      - ./frontend:/app # Szinkronizálja a fájlokat (Hot Reload)
      - /app/node_modules # A konténer saját moduljait védi
    environment:
      - WATCHPACK_POLLING=true # Windows kompatibilitás

volumes:
  postgres_data: